package hooks

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func gitRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for _, args := range [][]string{{"init", "-q"}, {"config", "user.email", "t@t"}, {"config", "user.name", "t"}} {
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
	return dir
}

func write(t *testing.T, dir, rel, body string) {
	t.Helper()
	p := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(body), 0o755); err != nil {
		t.Fatal(err)
	}
}

// The whole point: a config present, nothing installed, and today nothing says
// so. Six gates ran on nothing for weeks in a real project this way.
func TestConfiguredButNotInstalledIsReported(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")

	fs := Check(dir)
	if len(fs) != 1 {
		t.Fatalf("got %d findings, want 1: %+v", len(fs), fs)
	}
	if fs[0].Manager != "pre-commit" {
		t.Errorf("manager = %q", fs[0].Manager)
	}
	if !strings.Contains(Format(fs), "running on nothing") {
		t.Errorf("the report does not say what is at stake:\n%s", Format(fs))
	}
}

// The permissive half. A guard that fired on every project would be turned off.
func TestInstalledHooksAreNotReported(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	write(t, dir, ".git/hooks/pre-commit", "#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n")

	if fs := Check(dir); len(fs) != 0 {
		t.Errorf("reported an installed hook manager: %+v", fs)
	}
}

// A hook that exists but was written by something else is NOT this manager
// being installed — the project's own gates are still enforced by nothing, and
// the presence of a file is exactly what would hide that.
func TestAForeignHookDoesNotCountAsInstalled(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	// Mentions the tool by name in prose, as windsock's real hand-written hook
	// does ("# Versioned pre-commit hook"). A name-based marker matched that and
	// reported the project as installed — a false negative on the exact case
	// this check exists for.
	write(t, dir, ".git/hooks/pre-commit", "#!/bin/sh\n# Versioned pre-commit hook, installed via core.hooksPath.\necho my own hook\n")

	fs := Check(dir)
	if len(fs) != 1 {
		t.Fatalf("a hand-written hook was accepted as pre-commit being installed: %+v", fs)
	}
	if fs[0].ForeignHook == "" {
		t.Fatal("the finding does not record that a DIFFERENT hook is present — the report would then " +
			"claim nothing runs, which is false and is how a check earns being ignored")
	}
	out := Format(fs)
	if strings.Contains(out, "nothing in") {
		t.Errorf("report claims nothing runs when a foreign hook is installed:\n%s", out)
	}
	if !strings.Contains(out, "may be deliberate") {
		t.Errorf("report does not allow for a project enforcing the same rules its own way:\n%s", out)
	}
	// windsock is the live instance: core.hooksPath -> scripts/githooks, holding a
	// versioned pre-commit that does the same job by hand.
	if !strings.Contains(out, "enforced by nothing") {
		t.Errorf("report does not say what IS still true — that this config reaches nothing:\n%s", out)
	}
}

// The measured case. A redundant core.hooksPath pointing at the DEFAULT location
// changes no behaviour except to make `pre-commit install` refuse — so the
// report has to name it, or the reader has no way to know why installing failed.
func TestRedundantHooksPathIsNamedInTheReport(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	cmd := exec.Command("git", "config", "--local", "core.hooksPath", filepath.Join(dir, ".git", "hooks"))
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("setting core.hooksPath: %v\n%s", err, out)
	}

	fs := Check(dir)
	if len(fs) != 1 {
		t.Fatalf("got %d findings, want 1", len(fs))
	}
	if fs[0].HooksPathSet == "" {
		t.Fatal("core.hooksPath was set but the finding does not record it — the report would tell the " +
			"reader to run `pre-commit install`, which is exactly what refuses while it is set")
	}
	out := Format(fs)
	for _, want := range []string{"core.hooksPath", "--unset-all", "REFUSES"} {
		if !strings.Contains(out, want) {
			t.Errorf("report is missing %q:\n%s", want, out)
		}
	}
}

// A project configuring no hook manager must produce nothing, and a directory
// that is not a checkout must not error — audit runs against both.
func TestNoConfigAndNoRepoAreQuiet(t *testing.T) {
	if fs := Check(gitRepo(t)); len(fs) != 0 {
		t.Errorf("reported a project that configures no hooks: %+v", fs)
	}
	if fs := Check(t.TempDir()); len(fs) != 0 {
		t.Errorf("reported a non-repository: %+v", fs)
	}
}

// The mixed ios+web collision. Both profiles ship a hook manager, both write
// .git/hooks, and the last `install` wins. Reporting the loser as a bare
// "configured but not installed" invites the reflex fix — reinstall it — which
// DISABLES the gates the winner is currently running.
//
// multimeter is the live instance: lefthook won, and its web checks caught a
// Biome complexity violation, a tsc exactOptionalPropertyTypes error and a
// secrets-scan hit in one week, while pre-commit's Swift hooks had no Swift on
// disk to look at. The profile's own guidance said to hand the hooks to
// pre-commit, which would have been strictly worse.
func TestRivalManagerIsNamedNotJustReportedMissing(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	write(t, dir, "lefthook.yml", "pre-commit:\n  commands: {}\n")
	// lefthook's generated hook, identified by the shell function it defines
	// rather than by its name.
	write(t, dir, ".git/hooks/pre-commit", "#!/bin/sh\ncall_lefthook()\n{\n  :\n}\ncall_lefthook run pre-commit\n")

	fs := Check(dir)
	if len(fs) != 1 {
		t.Fatalf("expected exactly the pre-commit finding, got %+v", fs)
	}
	if fs[0].Manager != "pre-commit" {
		t.Fatalf("wrong manager reported: %+v", fs[0])
	}
	if fs[0].Rival != "lefthook" {
		t.Fatalf("the rival manager was not identified; the report cannot then distinguish a "+
			"mixed-repo collision from an unexplained gap: %+v", fs[0])
	}

	out := Format(fs)
	if !strings.Contains(out, "which this lacquer also ships") {
		t.Errorf("report does not say the winner is the lacquer's own other manager:\n%s", out)
	}
	if !strings.Contains(out, "DO NOT reflexively reinstall") {
		t.Errorf("report does not warn against the remedy that disables working gates:\n%s", out)
	}
	if !strings.Contains(out, "guards code that actually EXISTS") {
		t.Errorf("report does not give the actual decision rule:\n%s", out)
	}
	// The "may be deliberate" hedge is for an unknown foreign hook. Here the
	// cause is known, and saying "may be deliberate" would understate it.
	if strings.Contains(out, "may be deliberate") {
		t.Errorf("report hedges on a collision it can name precisely:\n%s", out)
	}
}

// The composed setup from #303. lefthook owns .git/hooks and its config calls
// `pre-commit run`, so BOTH rule sets execute from one installed hook.
//
// Reporting that as broken would be the worst outcome available: it trains
// people to ignore the finding on exactly the repos that resolved the collision
// correctly, and the "obvious" remedy — `pre-commit install` — would take the
// hooks back and silence lefthook's own gates.
func TestABridgedManagerIsReportedAsWorking(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	write(t, dir, "lefthook.yml", "pre-commit:\n  commands:\n    ios-pre-commit:\n      run: pre-commit run --hook-stage pre-commit\n")
	write(t, dir, ".git/hooks/pre-commit", "#!/bin/sh\ncall_lefthook()\n{\n  :\n}\n")

	fs := Check(dir)
	if len(fs) != 1 {
		t.Fatalf("expected the pre-commit finding, got %+v", fs)
	}
	if !fs[0].Bridged {
		t.Fatalf("a lefthook.yml that calls `pre-commit run` was not detected as bridging: %+v", fs[0])
	}
	out := Format(fs)
	if !strings.Contains(out, "these rules DO run") {
		t.Errorf("report does not say the bridged rules execute:\n%s", out)
	}
	if !strings.Contains(out, "Nothing to fix") {
		t.Errorf("report does not tell the reader this is the resolved state:\n%s", out)
	}
	if strings.Contains(out, "DO NOT reflexively reinstall") {
		t.Errorf("report still uses the unbridged collision wording:\n%s", out)
	}
}

// And the collision case must NOT be mistaken for the bridged one.
func TestAnUnbridgedRivalIsStillReportedAsAConflict(t *testing.T) {
	dir := gitRepo(t)
	write(t, dir, ".pre-commit-config.yaml", "repos: []\n")
	write(t, dir, "lefthook.yml", "pre-commit:\n  commands:\n    biome:\n      run: biome ci\n")
	write(t, dir, ".git/hooks/pre-commit", "#!/bin/sh\ncall_lefthook()\n{\n  :\n}\n")

	fs := Check(dir)
	if len(fs) != 1 || fs[0].Bridged {
		t.Fatalf("a lefthook.yml that never calls pre-commit was read as bridging: %+v", fs)
	}
	if !strings.Contains(Format(fs), "DO NOT reflexively reinstall") {
		t.Error("the unbridged collision lost its warning")
	}
}
