// Package hooks reports whether a project's configured git hooks would actually
// run on a commit.
//
// The gap this closes is not "the hooks are misconfigured" — it is that a repo
// can carry a fully correct hook config that is installed nowhere, and nothing
// says so. The manifest says the gates are active, the config file lists them,
// and every commit sails past all of them. It surfaces later as a violation
// reaching CI, which is the "local checks match CI" rule failing one level up:
// the local checks were not run at all.
//
// Measured case: a fleet project had `core.hooksPath` set, locally, to an
// ABSOLUTE path pointing at its own `.git/hooks` — functionally identical to
// the default, so nothing looked wrong and nothing behaved differently. But
// `pre-commit install` refuses outright while that key is set ("Cowardly
// refusing to install hooks with `core.hooksPath` set"), so the install had
// silently never happened and six configured gates — formatter, linter, doc
// lint, secret scan, model defaults, commit message — had never run on a single
// commit.
package hooks

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Manager is a hook runner a profile may ship a config for.
type Manager struct {
	Name       string // "pre-commit", "lefthook"
	ConfigFile string // the file whose presence means the project uses it
	// Marker identifies a hook script this manager GENERATED, so a hook written
	// by something else does not read as this one being installed.
	//
	// These are deliberately the generator's own fingerprint rather than its
	// name. The first version matched the bare name and produced a FALSE
	// NEGATIVE on windsock, whose hand-written hook opens "# Versioned
	// pre-commit hook" — the check saw the words, concluded pre-commit had
	// installed it, and reported nothing. A marker that a human writing about
	// the tool would also type cannot distinguish the tool's output from prose
	// about it.
	Marker string
}

var managers = []Manager{
	// pre-commit stamps every hook it writes with this exact line.
	{Name: "pre-commit", ConfigFile: ".pre-commit-config.yaml", Marker: "File generated by pre-commit"},
	// lefthook's generated hook defines this shell function; the string appears
	// in no prose about lefthook.
	{Name: "lefthook", ConfigFile: "lefthook.yml", Marker: "call_lefthook()"},
}

// Finding is one configured-but-not-running hook manager.
type Finding struct {
	Manager    string
	ConfigFile string
	HooksDir   string // where git will actually look
	// HooksPathSet is the value of a repo-local core.hooksPath, when set. It is
	// reported separately because it is both the usual cause and the one thing a
	// reader would not think to check: a redundant value pointing at the default
	// location changes no behaviour except to make installation refuse.
	HooksPathSet string
	// ForeignHook is a hook script present at HooksDir that this manager did not
	// write. It separates two situations a bare "not installed" would conflate:
	// nothing runs at all, versus something else runs instead. windsock is the
	// second -- it points core.hooksPath at a versioned scripts/githooks/ whose
	// pre-commit does the same job by hand. Reporting that as "nothing runs it"
	// would be false, and a check that mislabels a deliberate setup is one people
	// learn to skip past.
	ForeignHook string
	// Rival names the OTHER lacquer-shipped hook manager when that is what
	// wrote ForeignHook. Empty when the foreign hook came from anywhere else.
	//
	// Without it a mixed ios+web repo reads as "your hooks are broken", and the
	// obvious remedy makes things worse -- see Format.
	Rival string
	// Bridged is true when the rival's config invokes this manager, so this
	// config IS enforced -- just through the other hook rather than its own.
	//
	// Without this the composed setup that FIXES the collision still reports as
	// broken, which is the worst possible outcome: it trains people to ignore
	// the finding on precisely the repos that got it right.
	Bridged bool
}

// Check reports hook managers the project has configured whose hooks are not
// installed where git would run them.
//
// It answers the direct question — will a commit run these gates? — rather than
// inspecting configuration for known-bad shapes. A config-shape check can only
// find the causes somebody already thought of; this finds the ones nobody did,
// because the observable it tests is the one that matters.
//
// A project that configures no hook manager produces no findings, and a missing
// git repository is not an error: `lacquer audit` runs against directories that
// are not checkouts.
func Check(projectRoot string) []Finding {
	var out []Finding

	hooksDir, ok := effectiveHooksDir(projectRoot)
	if !ok {
		return nil
	}
	hooksPathSet, _ := gitConfig(projectRoot, "--local", "core.hooksPath")

	for _, m := range managers {
		if _, err := os.Stat(filepath.Join(projectRoot, m.ConfigFile)); err != nil {
			continue
		}
		if installed(hooksDir, m.Marker) {
			continue
		}
		rival := rivalInstalled(projectRoot, hooksDir, m.Name)
		out = append(out, Finding{
			Manager:      m.Name,
			ConfigFile:   m.ConfigFile,
			HooksDir:     hooksDir,
			HooksPathSet: hooksPathSet,
			ForeignHook:  foreignHook(hooksDir),
			Rival:        rival,
			Bridged:      rival != "" && bridges(projectRoot, rival, m.Name),
		})
	}
	return out
}

// installed reports whether a hook in dir was written by the named manager.
//
// It reads the script rather than only testing for existence, because the
// failure being guarded is a hook that runs SOMETHING — a hand-written one, or
// another manager's — while the project's config is enforced by nothing.
func installed(dir, marker string) bool {
	for _, name := range []string{"pre-commit", "pre-push", "commit-msg"} {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}
		if strings.Contains(string(b), marker) {
			return true
		}
	}
	return false
}

// effectiveHooksDir asks git where hooks live, so core.hooksPath is honoured
// rather than reimplemented. Reimplementing it is how a check ends up disagreeing
// with the thing it is checking.
// foreignHook names a hook script present but written by something else, or ""
// when the directory holds none.
func foreignHook(dir string) string {
	for _, name := range []string{"pre-commit", "commit-msg", "pre-push"} {
		p := filepath.Join(dir, name)
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() {
			return p
		}
	}
	return ""
}

func effectiveHooksDir(projectRoot string) (string, bool) {
	out, err := gitConfig(projectRoot, "rev-parse", "--git-path", "hooks")
	if err != nil || out == "" {
		return "", false
	}
	if !filepath.IsAbs(out) {
		out = filepath.Join(projectRoot, out)
	}
	return out, true
}

func gitConfig(projectRoot string, args ...string) (string, error) {
	if len(args) > 0 && args[0] != "rev-parse" {
		args = append([]string{"config"}, args...)
	}
	cmd := exec.Command("git", args...)
	cmd.Dir = projectRoot
	b, err := cmd.Output()
	return strings.TrimSpace(string(b)), err
}

// Format renders findings for `lacquer audit`. Empty when there are none, so the
// caller can print it unconditionally.
func Format(fs []Finding) string {
	if len(fs) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\ngit hooks configured but NOT installed:\n")
	for _, f := range fs {
		if f.ForeignHook != "" {
			b.WriteString("  " + f.ConfigFile + " (" + f.Manager + ") is not installed; a different hook runs instead:\n")
			b.WriteString("    " + f.ForeignHook + "\n")
			if f.Bridged {
				b.WriteString("    That is " + f.Rival + ", which this lacquer also ships — and its config CALLS\n")
				b.WriteString("    " + f.Manager + ", so these rules DO run. One installed hook, both rule sets.\n")
				b.WriteString("    Nothing to fix. Do NOT run `" + f.Manager + " install`: it would take .git/hooks\n")
				b.WriteString("    back from " + f.Rival + " and silence " + f.Rival + "'s own gates.\n")
				continue
			}
			if f.Rival != "" {
				// The other manager is one the lacquer itself ships, so this is
				// a known mixed-repo collision rather than an unexplained gap.
				// Saying so matters: both managers write .git/hooks and the last
				// `install` wins, and the reflex fix -- reinstall the one being
				// reported -- DISABLES whatever the winner was catching. In a
				// mixed ios+web repo with no Swift on disk yet, handing the
				// hooks back to pre-commit trades working web gates for iOS
				// gates that would run on nothing.
				b.WriteString("    That is " + f.Rival + ", which this lacquer also ships. Both write .git/hooks\n")
				b.WriteString("    and the last `install` wins, so this is a collision, not a missing setup.\n")
				b.WriteString("    DO NOT reflexively reinstall " + f.Manager + ": that disables " + f.Rival + "'s gates.\n")
				b.WriteString("    Whichever manager guards code that actually EXISTS should own the hooks.\n")
			} else {
				b.WriteString("    That may be deliberate — a project can enforce the same rules its own way.\n")
			}
			b.WriteString("    Either way, " + f.ConfigFile + " is enforced by nothing here, so a rule added to\n")
			b.WriteString("    it upstream will not reach this checkout.\n")
			continue
		}
		b.WriteString("  " + f.ConfigFile + " (" + f.Manager + ") — nothing in " + f.HooksDir + " runs it\n")
		if f.HooksPathSet != "" {
			b.WriteString("    core.hooksPath is set locally to " + f.HooksPathSet + "\n")
			b.WriteString("    `pre-commit install` REFUSES while that is set, even when the value points at\n")
			b.WriteString("    the default location and changes nothing else. Clear it and reinstall:\n")
			b.WriteString("      git config --unset-all core.hooksPath && " + f.Manager + " install\n")
		} else {
			b.WriteString("    install them:  " + f.Manager + " install\n")
		}
	}
	b.WriteString("\nEvery gate in that file is currently running on nothing. A violation it would\n")
	b.WriteString("have caught reaches CI instead, which is the local-checks-match-CI rule failing\n")
	b.WriteString("one level up: the local checks were never run.\n")
	return b.String()
}

// rivalInstalled names the OTHER lacquer-shipped hook manager when that manager
// both has a config here and actually wrote the installed hook.
//
// Both conditions matter. A project could carry a foreign hook from anywhere;
// only when the winner is the lacquer's own other manager is this the known
// mixed ios+web collision, where the reflex remedy — reinstall the one being
// reported — turns off gates that are currently working.
func rivalInstalled(projectRoot, hooksDir, self string) string {
	for _, m := range managers {
		if m.Name == self {
			continue
		}
		if _, err := os.Stat(filepath.Join(projectRoot, m.ConfigFile)); err != nil {
			continue
		}
		if installed(hooksDir, m.Marker) {
			return m.Name
		}
	}
	return ""
}

// bridges reports whether the installed rival's config invokes `self`, which is
// how a mixed ios+web repo runs both rule sets from one hook (#303): lefthook
// owns .git/hooks and calls `pre-commit run` from a command.
//
// A substring match on the invocation, deliberately, rather than parsing the
// config: the question is only "does this file call that binary", and a YAML
// walk would have to know every place a command can hide.
func bridges(projectRoot, rival, self string) bool {
	for _, m := range managers {
		if m.Name != rival {
			continue
		}
		data, err := os.ReadFile(filepath.Join(projectRoot, m.ConfigFile))
		if err != nil {
			return false
		}
		return strings.Contains(string(data), self+" run")
	}
	return false
}
