version: 2

project_name: lacquer

builds:
  - id: lacquer
    main: ./cmd/lacquer
    binary: lacquer
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - id: lacquer
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]-]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]-]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: patrickserrano
    name: lacquer
