// Package version reads and compares the lacquer repo's version, which is
// stamped into every managed region marker so `lacquer status` can tell a project
// whether the content it holds is current.
//
// The version is semver, derived from conventional commits by svu in CI (see
// .github/workflows/version.yml) — no human picks it, because doing so produced
// both a missed-bump gap (v0.69.0 does not exist) and a collision where two open
// PRs bumped to the same number and git merged it cleanly.
//
// A bare integer is accepted as the legacy form. release.yml has always tagged
// v0.${VERSION}.0, so the old counter N has a canonical embedding as 0.N.0. That
// embedding is what lets a project still stamped `v72` be ordered against a new
// 0.73.0 rather than being incomparable — no flag day, and stamps update on the
// project's next sync.
package version

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// Version is a semver triple. Prerelease and build metadata are deliberately not
// modeled: these values are generated by our own CI, never accepted from
// elsewhere, so the extra spec surface would be dead code.
type Version struct {
	Major, Minor, Patch int
}

// Parse reads "MAJOR.MINOR.PATCH", tolerating a leading "v" and surrounding
// whitespace. A bare integer N parses as 0.N.0 (the legacy content counter).
func Parse(s string) (Version, error) {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "v")
	if s == "" {
		return Version{}, fmt.Errorf("empty version")
	}

	parts := strings.Split(s, ".")
	switch len(parts) {
	case 1:
		n, err := parseComponent(parts[0])
		if err != nil {
			return Version{}, fmt.Errorf("invalid version %q: %w", s, err)
		}
		return Version{Minor: n}, nil // legacy N -> 0.N.0
	case 3:
		var v Version
		out := [3]*int{&v.Major, &v.Minor, &v.Patch}
		for i, p := range parts {
			n, err := parseComponent(p)
			if err != nil {
				return Version{}, fmt.Errorf("invalid version %q: %w", s, err)
			}
			*out[i] = n
		}
		return v, nil
	default:
		return Version{}, fmt.Errorf("invalid version %q: want MAJOR.MINOR.PATCH or a bare integer", s)
	}
}

// parseComponent accepts only a non-negative decimal integer. strconv.Atoi alone
// would accept "-1" and "+1", which are not valid semver components.
func parseComponent(s string) (int, error) {
	if s == "" {
		return 0, fmt.Errorf("empty component")
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return 0, fmt.Errorf("component %q is not a non-negative integer", s)
		}
	}
	return strconv.Atoi(s)
}

// String renders the canonical "MAJOR.MINOR.PATCH" form, with no leading "v".
func (v Version) String() string {
	return fmt.Sprintf("%d.%d.%d", v.Major, v.Minor, v.Patch)
}

// Less reports whether v precedes o. Components are compared numerically, most
// significant first, so 0.9.0 < 0.10.0 (a lexical compare would get this wrong).
func (v Version) Less(o Version) bool {
	if v.Major != o.Major {
		return v.Major < o.Major
	}
	if v.Minor != o.Minor {
		return v.Minor < o.Minor
	}
	return v.Patch < o.Patch
}

// Read returns the version recorded in <lacquerRoot>/VERSION.
func Read(lacquerRoot string) (Version, error) {
	path := filepath.Join(lacquerRoot, "VERSION")
	raw, err := os.ReadFile(path)
	if err != nil {
		return Version{}, err
	}
	v, err := Parse(string(raw))
	if err != nil {
		return Version{}, fmt.Errorf("read %s: %w", path, err)
	}
	return v, nil
}

// MarshalJSON writes the canonical string form ("0.73.0"), not a struct dump, so
// .lacquer.lock stays human-readable and diffable.
func (v Version) MarshalJSON() ([]byte, error) {
	return []byte(`"` + v.String() + `"`), nil
}

// UnmarshalJSON accepts the string form and, for back-compat, a bare JSON number.
//
// Every project synced before semver has `"version": 72` in its .lacquer.lock.
// Rejecting that would make lock.Read return an error, which takes audit's
// three-way comparison offline for that project — a much worse outcome than the
// small amount of leniency here. A legacy number means 0.N.0, the same embedding
// Parse uses.
func (v *Version) UnmarshalJSON(data []byte) error {
	s := strings.TrimSpace(string(data))
	if s == "null" {
		return nil // leave the zero value, consistent with encoding/json
	}
	// Unquote a JSON string; a bare number is passed through to Parse as-is.
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		s = s[1 : len(s)-1]
	} else if s == "" || s[0] < '0' || s[0] > '9' {
		// Not a string and not a number: reject rather than silently zero-valuing
		// (an object or bool would otherwise parse as 0.0.0).
		return fmt.Errorf("cannot unmarshal %s into a version", data)
	}
	parsed, err := Parse(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}
