package shipped

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// Every file sync renders must be a function of COMMITTED inputs only.
//
// `sync` runs on a developer's machine, where an XcodeGen project has usually
// been generated; `lacquer audit` re-renders in CI, on a clean checkout where it
// has not. If any rendered byte depended on the generated project, the two would
// disagree, and CI would report a correct sync as drift — or, worse, a project
// whose spec changed would render one thing locally and another in CI with no
// way to tell which was right. A fleet dry-run run on the same machine as the
// generated projects cannot see this: both of its renders have the project.
//
// So these tests render each fixture twice, once as CI sees it (no generated
// project on disk) and once as a developer's machine does (the generated
// project present but uncommitted), and require byte-identical output.

// generatedRoot holds generated projects for fixtures that commit none: the real
// `xcodegen generate` output of the fixture's project.yml, kept outside the
// fixture so the fixture stays in its pre-generation state.
func generatedRoot(t *testing.T) string {
	t.Helper()
	return filepath.Join(root(t), "internal", "shipped", "testdata", "generated")
}

// generatedFiles returns the files `xcodegen generate` would put inside the
// fixture's .xcodeproj, keyed by path relative to the repository root. A
// fixture that commits its project contributes every file in it except
// Package.resolved, which an XcodeGen project commits (it is the lockfile, and
// Dependabot reads it); one that commits none must have a generated copy under
// testdata/generated, or it is not covered and the test says so.
func generatedFiles(t *testing.T, fixture, xcodeproj string) map[string][]byte {
	t.Helper()
	src := filepath.Join(root(t), "internal", "shipped", "testdata", "projects", fixture, filepath.FromSlash(xcodeproj))
	if _, err := os.Stat(src); os.IsNotExist(err) {
		src = filepath.Join(generatedRoot(t), fixture, filepath.Base(xcodeproj))
	}
	if _, err := os.Stat(filepath.Join(src, "project.pbxproj")); err != nil {
		t.Fatalf("fixture %s declares %s but there is no generated project.pbxproj for it (commit `xcodegen generate` output under testdata/generated/%s): %v",
			fixture, xcodeproj, fixture, err)
	}
	out := map[string][]byte{}
	err := filepath.Walk(src, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || info.Name() == "Package.resolved" {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(filepath.Join(filepath.FromSlash(xcodeproj), rel))] = data
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// xcodegenOnly prepares fixture in the state an XcodeGen-only repository is
// committed in: the generated files are removed and ignored, everything else
// (Package.resolved included) is committed. With generated set, the generated
// project is then written back as it would be after `xcodegen generate`:
// present, ignored, uncommitted. manifest, if non-empty, is appended to the
// fixture's .lacquer.toml before the commit.
//
// A fixture that commits its project has no project.yml, and without one a
// missing pbxproj is a broken project rather than a generated one (sync refuses
// it, correctly), so a minimal spec is committed beside it.
func xcodegenOnly(t *testing.T, fixture, xcodeproj, manifest string, gen map[string][]byte, generated bool) *project {
	t.Helper()
	lacquerRoot := root(t)
	dst := t.TempDir()
	copyTree(t, filepath.Join(lacquerRoot, "internal", "shipped", "testdata", "projects", fixture), dst)
	spec := filepath.Join(dst, filepath.FromSlash(filepath.ToSlash(filepath.Dir(xcodeproj))), "project.yml")
	if _, err := os.Stat(spec); os.IsNotExist(err) {
		name := strings.TrimSuffix(filepath.Base(xcodeproj), ".xcodeproj")
		appendFile(t, spec, "name: "+name+"\n")
	}

	var ignore strings.Builder
	ignore.WriteString("\n# generated by xcodegen\n")
	var rels []string
	for rel := range gen {
		rels = append(rels, rel)
	}
	sort.Strings(rels) // both renders must commit the same .gitignore
	for _, rel := range rels {
		_ = os.Remove(filepath.Join(dst, filepath.FromSlash(rel)))
		ignore.WriteString("/" + rel + "\n")
	}
	appendFile(t, filepath.Join(dst, ".gitignore"), ignore.String())
	if manifest != "" {
		appendFile(t, filepath.Join(dst, ".lacquer.toml"), manifest)
	}
	initRepo(t, dst)

	if generated {
		for rel, data := range gen {
			p := filepath.Join(dst, filepath.FromSlash(rel))
			if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(p, data, 0o644); err != nil {
				t.Fatal(err)
			}
		}
		// The generated project must be on disk and invisible to git, or this
		// is not the developer's-machine state it claims to be.
		if st := gitIn(t, dst, "status", "--porcelain"); strings.TrimSpace(st) != "" {
			t.Fatalf("the generated project is not ignored in %s:\n%s", fixture, st)
		}
	}
	return &project{root: dst, lacquerRoot: lacquerRoot, t: t}
}

func appendFile(t *testing.T, path, text string) {
	t.Helper()
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if _, err := f.WriteString(text); err != nil {
		t.Fatal(err)
	}
}

// renderedTree is every text file in a synced project except .git and the
// generated project itself, which by construction differs between the two.
func renderedTree(t *testing.T, p *project, gen map[string][]byte) map[string][]byte {
	t.Helper()
	out := map[string][]byte{}
	walkSynced(t, p.root, func(rel string, data []byte) {
		if _, isGen := gen[rel]; !isGen {
			out[rel] = data
		}
	})
	return out
}

// syncBoth syncs fixture with and without its generated project and fails on
// any difference in what was rendered. It returns the clean (CI-side) project.
func syncBoth(t *testing.T, fixture, manifest string) *project {
	t.Helper()
	xcodeproj := fixtureXcodeproj(t, fixture)
	gen := generatedFiles(t, fixture, xcodeproj)
	hideXcodegen(t)

	clean := xcodegenOnly(t, fixture, xcodeproj, manifest, gen, false)
	dev := xcodegenOnly(t, fixture, xcodeproj, manifest, gen, true)
	clean.sync()
	dev.sync()
	pbx := filepath.Join(filepath.FromSlash(xcodeproj), "project.pbxproj")
	if _, err := os.Stat(filepath.Join(clean.root, pbx)); !os.IsNotExist(err) {
		t.Fatalf("%s: the CI-side render had a %s on disk (err=%v), so it is not the CI state", fixture, pbx, err)
	}
	if _, err := os.Stat(filepath.Join(dev.root, pbx)); err != nil {
		t.Fatalf("%s: the developer-side render had no %s: %v", fixture, pbx, err)
	}

	a, b := renderedTree(t, clean, gen), renderedTree(t, dev, gen)
	var names []string
	for rel := range a {
		names = append(names, rel)
	}
	for rel := range b {
		if _, ok := a[rel]; !ok {
			names = append(names, rel)
		}
	}
	sort.Strings(names)
	if len(a) == 0 {
		t.Fatalf("%s: sync rendered nothing, so the comparison proved nothing", fixture)
	}
	for _, rel := range names {
		x, inA := a[rel]
		y, inB := b[rel]
		switch {
		case !inA:
			t.Errorf("%s: %s is rendered only when the generated project exists", fixture, rel)
		case !inB:
			t.Errorf("%s: %s is rendered only when the generated project is absent", fixture, rel)
		case !bytes.Equal(x, y):
			t.Errorf("%s: %s renders differently with the generated project present — CI's audit, which has no generated project, will report a correct sync as drift", fixture, rel)
		}
	}
	return clean
}

// hideXcodegen removes xcodegen from PATH for the test. Sync regenerates a
// missing XcodeGen project itself when xcodegen is installed
// (baseline.EnsureXcodeproj), so on a Mac with it the "clean" render would
// quietly get a generated project too and the comparison would prove nothing.
// CI's Linux audit has no xcodegen.
func hideXcodegen(t *testing.T) {
	t.Helper()
	// A directory holding xcodegen is replaced by a mirror of everything else in
	// it, not dropped: on a Mac that directory is usually Homebrew's bin, and
	// dropping it would hide git-lfs and every other tool along with xcodegen.
	var keep []string
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if _, err := os.Stat(filepath.Join(dir, "xcodegen")); err != nil {
			keep = append(keep, dir)
			continue
		}
		mirror := t.TempDir()
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatal(err)
		}
		for _, e := range entries {
			if e.Name() == "xcodegen" {
				continue
			}
			if err := os.Symlink(filepath.Join(dir, e.Name()), filepath.Join(mirror, e.Name())); err != nil {
				t.Fatal(err)
			}
		}
		keep = append(keep, mirror)
	}
	t.Setenv("PATH", strings.Join(keep, string(os.PathListSeparator)))
	if _, err := exec.LookPath("xcodegen"); err == nil {
		t.Fatal("xcodegen is still on PATH")
	}
}

// fixtureXcodeproj is the project path the fixture's manifest declares.
func fixtureXcodeproj(t *testing.T, fixture string) string {
	t.Helper()
	p := &project{root: filepath.Join(root(t), "internal", "shipped", "testdata", "projects", fixture), t: t}
	return p.config().Project.Xcodeproj
}

// TestRenderDoesNotDependOnAGeneratedProject is the invariant, over every
// shipped fixture that declares an Xcode project.
func TestRenderDoesNotDependOnAGeneratedProject(t *testing.T) {
	entries, err := os.ReadDir(filepath.Join(root(t), "internal", "shipped", "testdata", "projects"))
	if err != nil {
		t.Fatal(err)
	}
	var covered []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		fixture := e.Name()
		if fixtureXcodeproj(t, fixture) == "" {
			continue // no Xcode project: nothing could be generated
		}
		covered = append(covered, fixture)
		t.Run(fixture, func(t *testing.T) { syncBoth(t, fixture, "") })
	}
	// A loop that silently found no fixtures would pass. These are the ones
	// that declare a project today; a new one is covered automatically.
	want := []string{"duoapp", "multistack", "multiswift", "rootapp", "watchapp"}
	if !reflect.DeepEqual(covered, want) {
		t.Fatalf("fixtures with an Xcode project = %v, want %v", covered, want)
	}
}

// TestWatchTestsRenderWithNoGeneratedProject: a watch test bundle declared in
// the manifest renders the Watch Tests job from the manifest alone, on a
// checkout with only project.yml, and identically with the project generated.
func TestWatchTestsRenderWithNoGeneratedProject(t *testing.T) {
	p := syncBoth(t, "watchapp", `
[project.watch_tests]
scheme      = "Watchapp Watch App"
test_target = "Watchapp Watch AppTests"
`)
	var doc watchDoc
	if err := yaml.Unmarshal([]byte(p.read(".github/workflows/ios-ci.yml")), &doc); err != nil {
		t.Fatalf("synced ios-ci.yml is not valid YAML: %v", err)
	}
	job, ok := doc.Jobs["watch-test"]
	if !ok {
		t.Fatal("[project.watch_tests] is declared, but the synced ios-ci.yml has no watch-test job")
	}
	legs := job.Strategy.Matrix["watch"]
	if len(legs) != 1 {
		t.Fatalf("got %d watch legs, want 1: %v", len(legs), legs)
	}
	if legs[0]["scheme"] != "Watchapp Watch App" || legs[0]["test_target"] != "Watchapp Watch AppTests" {
		t.Errorf("watch leg = %v, want the declared scheme and test target", legs[0])
	}
}

// TestSyncedLintRunsOncePerComponent: an app component under ios/ beside a
// `stack = "ios"` package component under tools/ is linted as two groups, each
// from its own directory, and never as one run from the repository root (which
// would lint tools/ with the app's config, or twice).
func TestSyncedLintRunsOncePerComponent(t *testing.T) {
	p := fromFixture(t, "multiswift")
	p.sync()
	var doc iosCIJobs
	if err := yaml.Unmarshal([]byte(p.read(".github/workflows/ios-ci.yml")), &doc); err != nil {
		t.Fatalf("synced ios-ci.yml is not valid YAML: %v", err)
	}
	body := stepRun(t, doc, "lint", "Run SwiftLint")
	real, _ := filepath.EvalSymlinks(p.root)
	bin, log := recordingSwiftlint(t)
	out, code := runStepIn(t, p.root, body, bin)
	if code != 0 {
		t.Fatalf("Run SwiftLint exited %d on the synced fixture\n%s", code, out)
	}
	want := []string{
		real + "/ios | --strict --config .swiftlint.yml .",
		real + "/tools | --strict --config .swiftlint.yml .",
	}
	if got := runs(t, log); !reflect.DeepEqual(got, want) {
		t.Fatalf("swiftlint runs = %q, want one per component %q", got, want)
	}
	for _, group := range []string{"::group::SwiftLint: ios\n", "::group::SwiftLint: tools\n"} {
		if !strings.Contains(out, group) {
			t.Errorf("the log has no %q group\n%s", strings.TrimSpace(group), out)
		}
	}
	if strings.Contains(out, "::group::SwiftLint: .\n") {
		t.Errorf("the log has a root group \".\"\n%s", out)
	}
}
